org: tinux
app: view-spot-finder
service: view-spot-finder

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x

functions:
    getViewSpots:
        handler: src/functions/view_spots_finder.handler
        events:
            - http:
                  path: /
                  method: get

resources:
    Resources:
        MeshTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: Mesh
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
