org: tinux
app: view-spot-finder
service: view-spot-finder

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs14.x
    # update this as per iam guide at: https://www.serverless.com/framework/docs/providers/aws/guide/iam
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
          Resource:
              - arn:aws:dynamodb:us-east-1:222256869848:table/Mesh

functions:
    addElements:
        handler: src/functions/addElements.handler
        events:
            - http:
                  path: /
                  method: post

resources:
    Resources:
        MeshTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: Mesh
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
